import React,{useMemo,useState}from"react";
import{calcularOperacion,crearChequeVacio,calcularCheque}from"./motores/MotorDescuentoCheques";
const moneda=(v,m="Gs.")=>{const n=Number(v)||0;return m==="USD"?`USD ${new Intl.NumberFormat("es-PY",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)}`:`Gs. ${new Intl.NumberFormat("es-PY",{maximumFractionDigits:0}).format(n)}`};
const numero=(v,d=2)=>new Intl.NumberFormat("es-PY",{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v)||0);
const parseMonto=v=>{let s=String(v??"").trim().replace(/\s/g,"");if(!s)return 0;if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");else s=s.replace(/[^0-9.-]/g,"");const n=Number(s);return Number.isFinite(n)?n:0};
const entradaMonto=(v,m)=>{const n=Number(v)||0;return m==="USD"?new Intl.NumberFormat("es-PY",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n):new Intl.NumberFormat("es-PY",{maximumFractionDigits:0}).format(n)};
const hoy=()=>new Date().toISOString().slice(0,10);
export default function App(){
 const[vista,setVista]=useState("descuento"),[cliente,setCliente]=useState(""),[ruc,setRuc]=useState(""),[cuenta,setCuenta]=useState(""),[monedaOp,setMonedaOp]=useState("Gs."),[fechaOp,setFechaOp]=useState(hoy()),[producto,setProducto]=useState("Descuento de Cheques"),[tasa,setTasa]=useState(.17),[comision,setComision]=useState(1000000),[iva,setIva]=useState(.10),[gastos,setGastos]=useState(0),[base,setBase]=useState(360),[cheques,setCheques]=useState([{id:1,numero:"",banco:"",monto:0,vencimiento:""}]);
 const[c,setC]=useState(25000000),[dias,setDias]=useState(30),[tf,setTf]=useState(.12),[td,setTd]=useState(.18);
 const op=useMemo(()=>calcularOperacion({fechaOperacion:fechaOp,cheques,tasaDescuento:tasa,comision,iva,gastos,diasBase:base}),[fechaOp,cheques,tasa,comision,iva,gastos,base]);
 const quick=useMemo(()=>{const i=c*tf*(dias/360),n=c+i,f=td*(dias/360);return{i,n,f,cheque:f>=1?0:n/(1-f)}},[c,dias,tf,td]);
 const upd=(id,k,v)=>setCheques(a=>a.map(x=>x.id===id?{...x,[k]:v}:x));
 const add=()=>setCheques(a=>[...a,{...crearChequeVacio(),id:Date.now()}]);
 const del=id=>setCheques(a=>a.filter(x=>x.id!==id));
 return <div className="app-shell"><header className="topbar no-print"><div><div className="brand">SIMULADOR FINANCIERO</div><div className="brand-sub">Descuento de Cheques · versión 2.8</div></div><button className="secondary-btn" onClick={()=>window.print()}>Imprimir / PDF</button></header>
 <nav className="tabs no-print"><button className={vista==="descuento"?"tab active":"tab"} onClick={()=>setVista("descuento")}>Descuento de Cheques</button><button className={vista==="rapida"?"tab active":"tab"} onClick={()=>setVista("rapida")}>Simulación Rápida</button></nav>
 <main className="main"><section className="hero"><h1>SIMULADOR DE DESCUENTO DE CHEQUES</h1><p>Herramienta independiente para simular una operación y preparar su liquidación.</p></section>
 {vista==="descuento"?<>
 <section className="card"><div className="section-title">1. DATOS GENERALES</div><div className="form-grid"><label>Cliente</label><input value={cliente} onChange={e=>setCliente(e.target.value)} placeholder="Nombre o razón social"/><label>RUC</label><input value={ruc} onChange={e=>setRuc(e.target.value)}/><label>N.º de cuenta</label><input value={cuenta} onChange={e=>setCuenta(e.target.value)}/><label>Moneda</label><select value={monedaOp} onChange={e=>setMonedaOp(e.target.value)}><option>Gs.</option><option>USD</option></select><label>Fecha de operación</label><input type="date" value={fechaOp} onChange={e=>setFechaOp(e.target.value)}/><label>Producto / operación</label><input value={producto} onChange={e=>setProducto(e.target.value)}/></div></section>
 <section className="card"><div className="section-title">2. CONDICIONES FINANCIERAS</div><div className="form-grid"><label>Tasa de descuento anual</label><div className="suffix"><input type="number" min="0" step=".01" value={tasa*100} onChange={e=>setTasa(Number(e.target.value)/100)}/><span>%</span></div><label>Comisión por desembolso</label><input inputMode="decimal" value={entradaMonto(comision,monedaOp)} onChange={e=>setComision(parseMonto(e.target.value))}/><label>IVA</label><div className="suffix"><input type="number" min="0" step=".01" value={iva*100} onChange={e=>setIva(Number(e.target.value)/100)}/><span>%</span></div><label>Otros gastos</label><input inputMode="decimal" value={entradaMonto(gastos,monedaOp)} onChange={e=>setGastos(parseMonto(e.target.value))}/><label>Base de cálculo</label><select value={base} onChange={e=>setBase(Number(e.target.value))}><option value="360">360 días</option><option value="365">365 días</option></select></div></section>
 <section className="card"><div className="section-title-row"><div className="section-title">3. DETALLE DE CHEQUES</div><button className="add-btn no-print" onClick={add}>+ Agregar cheque</button></div><div className="table-wrap"><table><thead><tr><th>N.º</th><th>Cheque</th><th>Banco</th><th>Importe ({monedaOp})</th><th>Vencimiento</th><th>Días</th><th>Interés</th><th>Neto</th><th className="no-print"></th></tr></thead><tbody>{cheques.map((ch,i)=>{const x=calcularCheque(ch,fechaOp,tasa,base);return <tr key={ch.id}><td>{i+1}</td><td><input value={ch.numero} onChange={e=>upd(ch.id,"numero",e.target.value)}/></td><td><input value={ch.banco} onChange={e=>upd(ch.id,"banco",e.target.value)}/></td><td><input className="money-input" inputMode="decimal" value={entradaMonto(ch.monto,monedaOp)} onChange={e=>upd(ch.id,"monto",parseMonto(e.target.value))}/></td><td><input type="date" value={ch.vencimiento} onChange={e=>upd(ch.id,"vencimiento",e.target.value)}/></td><td className="number-cell">{x.dias}</td><td className="money-cell">{moneda(x.interes,monedaOp)}</td><td className="money-cell">{moneda(x.neto,monedaOp)}</td><td className="no-print"><button className="delete-btn" onClick={()=>del(ch.id)}>×</button></td></tr>})}</tbody></table></div></section>
 <section className="card"><div className="section-title">4. LIQUIDACIÓN DE LA OPERACIÓN</div><div className="liquidacion"><div><span>Importe bruto de cheques</span><strong>{moneda(op.importeBruto,monedaOp)}</strong></div><div><span>Intereses de descuento</span><strong>{moneda(op.intereses,monedaOp)}</strong></div><div><span>IVA sobre intereses</span><strong>{moneda(op.ivaIntereses,monedaOp)}</strong></div><div><span>Comisión</span><strong>{moneda(op.comision,monedaOp)}</strong></div><div><span>IVA sobre comisión</span><strong>{moneda(op.ivaComision,monedaOp)}</strong></div><div><span>Otros gastos</span><strong>{moneda(op.gastos,monedaOp)}</strong></div><div className="total-line"><span>IMPORTE NETO A DESEMBOLSAR</span><strong>{moneda(op.neto,monedaOp)}</strong></div></div><div className="summary-grid"><div><small>Cantidad de cheques</small><b>{cheques.length}</b></div><div><small>Plazo promedio ponderado</small><b>{numero(op.plazoPromedio,1)} días</b></div><div><small>Costo total</small><b>{moneda(op.costoTotal,monedaOp)}</b></div><div><small>Costo sobre bruto</small><b>{numero(op.costoPct,2)}%</b></div></div></section>
 <section className="card"><div className="section-title">5. REFERENCIA DE LA OPERACIÓN</div><div className="reference-box"><div><span>Cliente</span><b>{cliente||"No informado"}</b></div><div><span>RUC</span><b>{ruc||"No informado"}</b></div><div><span>Operación</span><b>{producto}</b></div><div><span>Moneda</span><b>{monedaOp}</b></div><div><span>Fecha</span><b>{fechaOp}</b></div></div></section>
 </>:<section className="card quick"><div className="section-title">SIMULACIÓN RÁPIDA</div><div className="form-grid"><label>Capital original</label><input inputMode="numeric" value={entero(c)} onChange={e=>setC(Number(e.target.value.replace(/\D/g,""))||0)}/><label>Días de nueva prórroga</label><input type="number" min="1" value={dias} onChange={e=>setDias(Number(e.target.value))}/><label>Tasa de financiación anual</label><div className="suffix"><input type="number" step=".01" value={tf*100} onChange={e=>setTf(Number(e.target.value)/100)}/><span>%</span></div><label>Tasa de descuento bancario anual</label><div className="suffix"><input type="number" step=".01" value={td*100} onChange={e=>setTd(Number(e.target.value)/100)}/><span>%</span></div></div><div className="liquidacion quick-results"><div><span>Interés por financiar</span><strong>{moneda(quick.i,"Gs.")}</strong></div><div><span>Total neto deseado</span><strong>{moneda(quick.n,"Gs.")}</strong></div><div><span>Factor de descuento</span><strong>{numero(quick.f,4)}</strong></div><div className="total-line"><span>VALOR MÍNIMO DEL NUEVO CHEQUE</span><strong>{moneda(quick.cheque,"Gs.")}</strong></div></div></section>}
 <footer className="no-print">Simulador independiente · No constituye una liquidación bancaria oficial</footer></main></div>;
}